export const theme = {
  colors: {
    primary: '#4A80F0',
    secondary: '#9D71E8',
    accent: '#4AD991',
    success: '#2ECC71',
    warning: '#F39C12',
    error: '#E74C3C',
    background: '#FFFFFF',
    card: '#F9FAFC',
    text: '#1A1A2E',
    subtext: '#666683',
    grey: '#9CA3AF',
    lightGrey: '#E5E7EB',
    black: '#000000',
    white: '#FFFFFF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 16,
    xl: 24,
    round: 999,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  fontFamily: {
    regular: 'Inter-Regular',
    semiBold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
    poppinsMedium: 'Poppins-Medium',
    poppinsSemiBold: 'Poppins-SemiBold',
    poppinsBold: 'Poppins-Bold',
  },
};